# Auto-generated by Notebook 9
# Final retrieval configurations for the Harry Potter RAG project.

RETRIEVAL_PROFILES = {
    "fast_minilm": {
        "alpha": 0.7,
        "description": "Fast profile: MiniLM-L6 with very low latency and strong hit@k. Tuned on NB8 qa_60_mixed (minilm_l6, \u03b1=0.70, k=17).",
        "k": 17,
        "model": "minilm_l6"
    },
    "max_precision_bge": {
        "alpha": 0.45,
        "description": "Max-precision profile: bge-base tuned on NB8 qa_60_mixed for highest early precision; higher latency.",
        "k": 15,
        "model": "bge_base"
    },
    "prod_e5_balanced": {
        "alpha": 0.5,
        "description": "Production default: balanced accuracy and latency. Tuned on NB8 qa_60_mixed (e5_small, \u03b1=0.50, k=16).",
        "k": 16,
        "model": "e5_small"
    }
}

DEFAULT_PROFILE_NAME = 'prod_e5_balanced'
